name: nextcloud
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
     - 1234:80
    restart: unless-stopped
