services:
  linkding:
    container_name: "linkding"
    image: sissbruecker/linkding:latest
    ports:
      - "9090:9090"
    volumes:
      - "./data:/etc/linkding/data"
    restart: unless-stopped